camera:
  - platform: ffmpeg
    name: Front Camera
    input: !secret front_stream_url
  - platform: ffmpeg
    name: Side Camera
    input: !secret side_stream_url
  - platform: ffmpeg
    name: Back Camera
    input: !secret back_stream_url

binary_sensor:
  - platform: hikvision
    host: !secret nvr_ip
    username: admin
    password: !secret nvr_password