automation: !include automations.yaml

group: !include groups.yaml

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

scene: !include scenes.yaml

script: !include scripts.yaml

frontend:
  themes: !include_dir_merge_named themes/
