config: {}

conversation: {}

spc:
  api_url: !secret spc_api_url
  ws_url: !secret spc_ws_url

wake_on_lan: {}

debugpy:
  start: true
  wait: false
  host: 0.0.0.0
  port: 5678

automation: {}
history: {}
logbook: {}
# map: {}
mobile_app: {}
# person: {}
# scene: {}
script: {}
sun: {}
system_health: {}
# zone: {}
input_boolean: {}
input_datetime: {}
input_text: {}
input_number: {}
input_select: {}
# ssdp: {}

# default_config: {}

# discovery:
#   enable:
  
cloud: {}

ffmpeg: {}

stream: {}

sensor:
- display_options:
  - time
  - date
  platform: time_date
- platform: authenticated

tts:
- platform: google_translate

zeroconf:

http:
  base_url: !secret external_url
  cors_allowed_origins:
    - https://cast.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
   - 10.0.0.0/8
   - 172.16.0.0/12
   - 192.168.0.0/16

updater:
  reporting: false
  include_used_components: true

circadian_lighting: {}

switch:
  - platform: circadian_lighting
    lights_ct:
      - light.back_room
      - light.bedroom_light
      - light.front_room_lamp
      - light.front_room_light
      - light.hallway_lights
      - light.landing_lights
      - light.master_bedroom_light
      - light.office_light
      - light.sitting_room_light
      - light.spare_bedroom_light
      - light.storage_light
      - light.top_floor_bedroom_bathroom_light
      - light.top_floor_landing_light

homekit:
- filter:
    include_domains:
      - cover
      - alarm_control_panel
      - climate
      - vacuum
    include_entities:
      - light.front_room_light
      - switch.christmas_tree
      - light.hallway_lights
      - light.back_room
      - light.dining_light
      - light.office_light
      - light.kitchen_light
      - light.bedroom_light
      - light.landing_lights
      - camera.doorstation_1ccae372949f_live
      - light.front_door
      - light.front_room_lamp
      - camera.back
      - camera.front
      - camera.side
      - switch.garden_side_lights
    exclude_entity_globs:
      - cover.*raw*
      - media_player.*raw