config: {}

# debugpy:
#   host: 0.0.0.0
#   port: 5678
#   start: true

conversation: {}

spc:
  api_url: http://192.168.20.190:8088
  ws_url: ws://192.168.20.190:8088/ws/spc

automation: {}
history: {}
logbook: {}
# map: {}
mobile_app: {}
# person: {}
# scene: {}
script: {}
sun: {}
system_health: {}
# zone: {}
input_boolean: {}
input_datetime: {}
input_text: {}
input_number: {}
input_select: {}
# ssdp: {}

# default_config: {}

# discovery:
#   enable:
  
cloud: {}

ffmpeg: {}

stream: {}

sensor:
- display_options:
  - time
  - date
  platform: time_date
- platform: authenticated

tts:
- platform: google_translate

zeroconf:


http:
  base_url: !secret external_url
  cors_allowed_origins:
    - https://cast.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
   - 10.0.0.0/8
   - 172.16.0.0/12
   - 192.168.0.0/16

updater:
  reporting: false
  include_used_components: true
