# Ref https://www.home-assistant.io/integrations/spotify/

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

sensor:
  - platform: spotcast
